server:
  port: 8889
spring:
  freemarker:
    suffix: .html
    cache: false
  application:
    name: nginx

page-store: 
  location: D:\store

nignx:
  config: C:/software/nginx-1.14.2/conf/nginx.conf
  path: C:/software/nginx-1.14.2/